// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	GetTodoParams
	AddTodoParams
	DeleteTodoParams
	TodoObject
	TodoResponse
	DeleteResponse
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTodoParams struct {
}

func (m *GetTodoParams) Reset()                    { *m = GetTodoParams{} }
func (m *GetTodoParams) String() string            { return proto.CompactTextString(m) }
func (*GetTodoParams) ProtoMessage()               {}
func (*GetTodoParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AddTodoParams struct {
	Task string `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *AddTodoParams) Reset()                    { *m = AddTodoParams{} }
func (m *AddTodoParams) String() string            { return proto.CompactTextString(m) }
func (*AddTodoParams) ProtoMessage()               {}
func (*AddTodoParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddTodoParams) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

type DeleteTodoParams struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteTodoParams) Reset()                    { *m = DeleteTodoParams{} }
func (m *DeleteTodoParams) String() string            { return proto.CompactTextString(m) }
func (*DeleteTodoParams) ProtoMessage()               {}
func (*DeleteTodoParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteTodoParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TodoObject struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Task string `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
}

func (m *TodoObject) Reset()                    { *m = TodoObject{} }
func (m *TodoObject) String() string            { return proto.CompactTextString(m) }
func (*TodoObject) ProtoMessage()               {}
func (*TodoObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TodoObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TodoObject) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

type TodoResponse struct {
	Todos []*TodoObject `protobuf:"bytes,1,rep,name=todos" json:"todos,omitempty"`
}

func (m *TodoResponse) Reset()                    { *m = TodoResponse{} }
func (m *TodoResponse) String() string            { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()               {}
func (*TodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TodoResponse) GetTodos() []*TodoObject {
	if m != nil {
		return m.Todos
	}
	return nil
}

type DeleteResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTodoParams)(nil), "todo.getTodoParams")
	proto.RegisterType((*AddTodoParams)(nil), "todo.addTodoParams")
	proto.RegisterType((*DeleteTodoParams)(nil), "todo.deleteTodoParams")
	proto.RegisterType((*TodoObject)(nil), "todo.todoObject")
	proto.RegisterType((*TodoResponse)(nil), "todo.todoResponse")
	proto.RegisterType((*DeleteResponse)(nil), "todo.deleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoService service

type TodoServiceClient interface {
	AddTodo(ctx context.Context, in *AddTodoParams, opts ...grpc.CallOption) (*TodoObject, error)
	DeleteTodo(ctx context.Context, in *DeleteTodoParams, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetTodos(ctx context.Context, in *GetTodoParams, opts ...grpc.CallOption) (*TodoResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) AddTodo(ctx context.Context, in *AddTodoParams, opts ...grpc.CallOption) (*TodoObject, error) {
	out := new(TodoObject)
	err := grpc.Invoke(ctx, "/todo.todoService/addTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeleteTodo(ctx context.Context, in *DeleteTodoParams, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/todo.todoService/deleteTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodos(ctx context.Context, in *GetTodoParams, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := grpc.Invoke(ctx, "/todo.todoService/getTodos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoService service

type TodoServiceServer interface {
	AddTodo(context.Context, *AddTodoParams) (*TodoObject, error)
	DeleteTodo(context.Context, *DeleteTodoParams) (*DeleteResponse, error)
	GetTodos(context.Context, *GetTodoParams) (*TodoResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_AddTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTodoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).AddTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.todoService/AddTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).AddTodo(ctx, req.(*AddTodoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.todoService/DeleteTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DeleteTodo(ctx, req.(*DeleteTodoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.todoService/GetTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodos(ctx, req.(*GetTodoParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.todoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addTodo",
			Handler:    _TodoService_AddTodo_Handler,
		},
		{
			MethodName: "deleteTodo",
			Handler:    _TodoService_DeleteTodo_Handler,
		},
		{
			MethodName: "getTodos",
			Handler:    _TodoService_GetTodos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xed, 0x4a, 0xc3, 0x40,
	0x10, 0x6c, 0x62, 0xb5, 0x3a, 0xb5, 0xb5, 0xac, 0x22, 0x21, 0xbf, 0xca, 0x09, 0x52, 0xfc, 0x51,
	0x24, 0xa2, 0xbf, 0x7c, 0x07, 0x25, 0xfa, 0x02, 0xd7, 0xde, 0x52, 0xa2, 0xd6, 0x2b, 0xd9, 0xc3,
	0x47, 0xf3, 0xf9, 0x24, 0xb9, 0xa4, 0x97, 0xc6, 0x7f, 0xfb, 0x35, 0x33, 0x3b, 0xbb, 0x80, 0xb3,
	0xc6, 0x2e, 0x77, 0xa5, 0x75, 0x96, 0x86, 0x55, 0xac, 0x2e, 0x30, 0xd9, 0xb0, 0x7b, 0xb7, 0xc6,
	0xbe, 0xea, 0x52, 0x6f, 0x45, 0xdd, 0x60, 0xa2, 0x8d, 0x09, 0x05, 0x22, 0x0c, 0x9d, 0x96, 0xcf,
	0x24, 0x9a, 0x47, 0x8b, 0xb3, 0xbc, 0x8e, 0x95, 0xc2, 0xcc, 0xf0, 0x17, 0x3b, 0xee, 0xcc, 0x4d,
	0x11, 0x17, 0xa6, 0x99, 0x8a, 0x0b, 0xa3, 0xee, 0xbd, 0xda, 0xcb, 0xea, 0x83, 0xd7, 0xae, 0xdf,
	0xdd, 0xb3, 0xc6, 0x1d, 0xd6, 0x27, 0x9c, 0x57, 0x88, 0x9c, 0x65, 0x67, 0xbf, 0x85, 0xe9, 0x16,
	0xc7, 0x55, 0x2e, 0x49, 0x34, 0x3f, 0x5a, 0x8c, 0xb3, 0xd9, 0xb2, 0xde, 0x3e, 0x90, 0xe6, 0xbe,
	0xad, 0xee, 0x30, 0xf5, 0xdb, 0xec, 0x91, 0x09, 0x46, 0x5b, 0x16, 0xd1, 0x1b, 0x6e, 0x24, 0xdb,
	0x34, 0xfb, 0x8d, 0x30, 0xae, 0x50, 0x6f, 0x5c, 0xfe, 0x14, 0x6b, 0xa6, 0x0c, 0xa3, 0xc6, 0x2e,
	0x5d, 0x7a, 0xfe, 0x03, 0xf7, 0xe9, 0x3f, 0x51, 0x35, 0xa0, 0x67, 0x20, 0xb8, 0xa7, 0x6b, 0x3f,
	0xd1, 0xbf, 0x47, 0x7a, 0xd5, 0xad, 0xb7, 0x9b, 0xa9, 0x01, 0x3d, 0xe2, 0xb4, 0xb9, 0xb8, 0xb4,
	0x92, 0x07, 0x1f, 0x48, 0x29, 0x48, 0x06, 0xd8, 0xea, 0xa4, 0xfe, 0xda, 0xc3, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x64, 0x7f, 0x69, 0x7e, 0xc3, 0x01, 0x00, 0x00,
}
